"""PostImage collection_id removed

Revision ID: 005d89ea6726
Revises: 8f6f9a219c5f
Create Date: 2024-04-25 11:53:26.875015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "005d89ea6726"
down_revision: Union[str, None] = "8f6f9a219c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post_images", "collection_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_images",
        sa.Column("collection_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
