"""product added

Revision ID: 1a4edfb3dcbc
Revises: 005d89ea6726
Create Date: 2024-04-25 18:04:45.962814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a4edfb3dcbc"
down_revision: Union[str, None] = "005d89ea6726"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("name", sa.String(length=50), nullable=False))
    op.add_column(
        "products",
        sa.Column(
            "type",
            sa.Enum("PAN", "SKILLET", "LID", "ELEC", "OTHER", name="producttypeenum"),
            nullable=False,
        ),
    )
    op.add_column(
        "products", sa.Column("price", sa.DECIMAL(precision=7, scale=2), nullable=True)
    )
    op.add_column("products", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column(
        "products",
        sa.Column("capacity", sa.DECIMAL(precision=3, scale=1), nullable=True),
    )
    op.add_column(
        "products", sa.Column("description", sa.String(length=255), nullable=True)
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=True)
    op.create_index(op.f("ix_products_price"), "products", ["price"], unique=False)
    op.create_index(op.f("ix_products_type"), "products", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_type"), table_name="products")
    op.drop_index(op.f("ix_products_price"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_column("products", "description")
    op.drop_column("products", "capacity")
    op.drop_column("products", "width")
    op.drop_column("products", "height")
    op.drop_column("products", "price")
    op.drop_column("products", "type")
    op.drop_column("products", "name")
    # ### end Alembic commands ###
