"""renamed from_user to user_id in replyModel

Revision ID: 6922de55df87
Revises: e2e844659eac
Create Date: 2024-04-10 14:45:31.010248

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6922de55df87'
down_revision: Union[str, None] = 'e2e844659eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.add_column('replies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_replies_from_user', table_name='replies')
    op.create_index(op.f('ix_replies_user_id'), 'replies', ['user_id'], unique=False)
    op.drop_constraint('replies_from_user_fkey', 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'users', ['user_id'], ['id'])
    op.drop_column('replies', 'from_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('from_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key('replies_from_user_fkey', 'replies', 'users', ['from_user'], ['id'])
    op.drop_index(op.f('ix_replies_user_id'), table_name='replies')
    op.create_index('ix_replies_from_user', 'replies', ['from_user'], unique=False)
    op.drop_column('replies', 'user_id')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    # ### end Alembic commands ###
