"""adding notifications

Revision ID: 8b3ef93d1aec
Revises: 8ca24135cbd2
Create Date: 2024-04-15 20:56:19.253589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3ef93d1aec'
down_revision: Union[str, None] = '8ca24135cbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('type', sa.Enum('LIKE', 'REPLY', 'COMMENT', name='notificationtypeenum'), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_notifications_profile_id'), 'notifications', ['profile_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_foreign_key(None, 'notifications', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_profile_id'), table_name='notifications')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'profile_id')
    # ### end Alembic commands ###
