"""added PostImage

Revision ID: 8f6f9a219c5f
Revises: 2f2c256e3bb7
Create Date: 2024-04-25 10:44:53.428082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6f9a219c5f'
down_revision: Union[str, None] = '2f2c256e3bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('post_images', sa.Column('path', sa.String(), nullable=True))
    op.add_column('post_images', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_images_post_id'), 'post_images', ['post_id'], unique=False)
    op.create_foreign_key(None, 'post_images', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_images', type_='foreignkey')
    op.drop_index(op.f('ix_post_images_post_id'), table_name='post_images')
    op.drop_column('post_images', 'collection_id')
    op.drop_column('post_images', 'path')
    op.drop_column('post_images', 'post_id')
    # ### end Alembic commands ###
