"""cascade on every foreignKey

Revision ID: 96c9052eefbb
Revises: f795108cf594
Create Date: 2024-04-11 22:39:20.344130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c9052eefbb'
down_revision: Union[str, None] = 'f795108cf594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profile_avatars_profile_id_fkey', 'profile_avatars', type_='foreignkey')
    op.create_foreign_key(None, 'profile_avatars', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profiles_user_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('replies_user_id_fkey', 'replies', type_='foreignkey')
    op.drop_constraint('replies_to_user_fkey', 'replies', type_='foreignkey')
    op.drop_constraint('replies_comment_id_fkey', 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'users', ['to_user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'replies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'replies', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key('replies_comment_id_fkey', 'replies', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key('replies_to_user_fkey', 'replies', 'users', ['to_user'], ['id'])
    op.create_foreign_key('replies_user_id_fkey', 'replies', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'profile_avatars', type_='foreignkey')
    op.create_foreign_key('profile_avatars_profile_id_fkey', 'profile_avatars', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
