"""removed likes from parent models

Revision ID: 9ca4f4c8b166
Revises: 0ac0787fe55f
Create Date: 2024-04-12 13:46:35.831344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca4f4c8b166'
down_revision: Union[str, None] = '0ac0787fe55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
