"""user_likes relationship in user model

Revision ID: d0613ec09b2a
Revises: 1a4edfb3dcbc
Create Date: 2024-06-19 12:35:58.256057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0613ec09b2a'
down_revision: Union[str, None] = '1a4edfb3dcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
