"""added replies

Revision ID: e2e844659eac
Revises: e7044a42a4ca
Create Date: 2024-04-08 13:09:07.746716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e844659eac'
down_revision: Union[str, None] = 'e7044a42a4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('to_user', sa.Integer(), nullable=True),
    sa.Column('from_user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_comment_id'), 'replies', ['comment_id'], unique=False)
    op.create_index(op.f('ix_replies_from_user'), 'replies', ['from_user'], unique=False)
    op.create_index(op.f('ix_replies_to_user'), 'replies', ['to_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_to_user'), table_name='replies')
    op.drop_index(op.f('ix_replies_from_user'), table_name='replies')
    op.drop_index(op.f('ix_replies_comment_id'), table_name='replies')
    op.drop_table('replies')
    # ### end Alembic commands ###
